"""delete the category  user.id

Revision ID: 08e2926f6d7e
Revises: 2ac2f9a5a54a
Create Date: 2019-11-24 19:47:00.172787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e2926f6d7e'
down_revision = '2ac2f9a5a54a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pitch_user_id_fkey', 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitch_user_id_fkey', 'pitch', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
