"""create the pass_code_secure column

Revision ID: d780aa9bdff9
Revises: 6d7771da1d90
Create Date: 2019-11-23 11:22:26.989739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd780aa9bdff9'
down_revision = '6d7771da1d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_code_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_code_secure')
    # ### end Alembic commands ###
