"""create the bio and profile_path  column on user table

Revision ID: eb52402f682e
Revises: 03e0f3acbac3
Create Date: 2019-11-23 21:59:44.390864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb52402f682e'
down_revision = '03e0f3acbac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
